version: "3.8"
networks:
  back-tier:
#networks:
#  mynetwork:
#    ipam:
#      config:
#        - subnet: 172.20.0.0/24
services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - ./../:/var/www/
    networks:
     - back-tier
#        ipv4_address: 110.20.0.60
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm
    networks:
     - back-tier
#        ipv4_address: 110.20.0.70
  #db
  postgres:
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - ${POSTGRES_PORT}:54322
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    networks:
     - back-tier
#        ipv4_address: 110.20.0.2
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672
    networks:
     - back-tier
#        ipv4_address: 110.20.0.90
  #Ansible Semaphore: Awesome Open Source Ansible GUI
  semaphore:
#    restart: unless-stopped
    ports:
      - 5434:54322
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: ${POSTGRES_USER}
      SEMAPHORE_DB_PASS: ${POSTGRES_PASSWORD}
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@example.com
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes'
      SEMAPHORE_LDAP_HOST: dc01.local.example.com
      SEMAPHORE_LDAP_PORT: '636'
      SEMAPHORE_LDAP_NEEDTLS: 'yes'
      SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
      SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
      SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
      SEMAPHORE_LDAP_SEARCH_FILTER: "(u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
    depends_on:
      - postgres
    networks:
     - back-tier
#        ipv4_address: 110.20.0.220
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|hoet|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/rum/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    networks:
     - back-tier
#        ipv4_address: 110.20.0.230
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.28.1
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus
    networks:
     - back-tier
#        ipv4_address: 110.20.0.240
  grafana:
    image: grafana/grafana:8.0.6-ubuntu
    container_name: grafana
    ports:
     - "3000:3000"
  #  volumes:
  #   - $DOCKERDIR/appdata/grafana:/var/lib/grafana
  #   - grafana-data:/var/lib/grafana
  #   - grafana-configs:/etc/grafana
    networks:
     - back-tier
#        ipv4_address: 110.20.0.250
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
#    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DOCKERDIRDOD/appdata/portainer/data:/data
    environment:
      - TZ=$TZ
    networks:
     - back-tier
#        ipv4_address: 110.20.1.160
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
   # restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
     - back-tier
#        ipv4_address: 110.20.1.170
# grafana - prometheus
volumes:
  #pgadmin
  local_pgdata:
  pgadmin-data:
  # grafana node-exporter prometheus
  grafana-logs:
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs:
  db_data:
  semaphore-postgres: # to use postgres, switch to: semaphore-postgres
