global:
  scrape_interval: 10s
  external_labels:
    monitor: 'lambda-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'

    static_configs:
      - targets: ['localhost:9090']